### ISSUE TITLE
Enabling vehicle avoidance has no effect on behavior

### ISSUE THREAD

**Issue by ItsTimmy** [duckietown/dt-core#33]
When launching the lane following demo, vehicle avoidance should be enabled, based on https://github.com/duckietown/dt-core/commit/a8f77d688199250328d0c15fab45ba7ba803a5a3 . The vehicle avoidance node publishes 2 topics:

 - `/HOSTNAME/vehicle_avoidance_control_node/car_cmd`
 - `/HOSTNAME/vehicle_avoidance_control_node/vehicle_detected`

According to `rostopic info`, there are no subscribers to either of these topics. 

Using `rostopic echo`, we can observe that these topics publish data as expected when approaching another vehicle. However, the duckiebot does not alter its behavior in any way in response to this.

Potentially related: In [`car_cmd_switch_node/default.yaml`](https://github.com/duckietown/dt-car-interface/blob/daffy/packages/dagu_car/config/car_cmd_switch_node/default.yaml), there is no mention of the `vehicle_avoidance_control_node/car_cmd` topic.

**Comment by liampaull** [comment]
@surirohit are you the right one for this?

**Comment by surirohit** [comment]
I'm on it

**Comment by surirohit** [comment]
https://github.com/duckietown/dt-car-interface/pull/4
