### ISSUE TITLE
matplotlib dependency?

### ISSUE THREAD

**Issue by afdaniele** [duckietown/dt-core#6]
https://github.com/duckietown/dt-core/blob/fa93a4d6143744098d46eca74239dea167169d77/dependencies-py.txt#L3

@AleksandarPetrov 
matplotlib is not a requirement but a dependency of reprep, right? In that case, we don't list it otherwise if we remove reprep in the future we will still keep matplotlib.

**Comment by AleksandarPetrov** [comment]
@afdaniele Absolutely! But my build failed and I think it is because `reprep` tried to install the latest version of `matplotlib` which is 3.sth and apparently works only with Python 3. If when removing this line the build still works, then remove it.

**Comment by AmaurX** [comment]
we should try the pip freeze that @AndreaCensi suggested

**Comment by liampaull** [comment]
it is removed and I have pinned a version of reprep
